[package]
name = "ferret"
version = "0.1.0"
authors = ["Tyler Hallada <tyler@hallada.net>"]

[dependencies]
termion = "1.5.1"
liner = "0.4.4"
reqwest = "0.9.4"
scraper = "0.8.1"
html2text = "0.1.8"

[dependencies.cursive]
version = "0.9.2"
default-features = false
features = ["termion-backend"]
